Vagrant.configure(2) do |config|

  config.vm.box = "rhel72x64"
  
  config.vm.provision :ansible do |ansible|
    ansible.playbook   = "provisioning/playbook.yml"
    ansible.extra_vars = { update: false }
  end
end
